openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /raeume:
    get:
      summary: Liste von Räumen.
      responses:
        '200':    # status code
          description: Ein JSON Array aus Raum Objekten
          content:
            application/json:
              schema: 
                type: array
                items:
                  type: object
                  properties:  
                    id:
                      type: integer
                    nr:
                      type: string
                    bezeichnung:
                      type: string
                    hat_notiz:
                      type: boolean
  /raum:
    get:
      summary: Infos zu einem Raum.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Raum'
    put:
      summary: Raum ändern.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nr:
                  type: string
                bezeichnung:
                  type: string
                notiz:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
    delete:
      summary: Raum ändern.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': 
          description: OK
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
    
  /raum/new:
    post:
      summary: Neuen Raum anlegen.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Raum'
      responses:
        '200': 
          description: OK
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
              


components:
  schemas:
    Raum:
      properties:
        id:
          type: integer
        nr:
          type: string
        bezeichnung:
          type: string
        notiz:
          type: string
      required:
        - id
        - nr
        - bezeichnung
        - notiz